#!/usr/bin/env node

/**
 * export-openapi.mjs
 *
 * Fetches the OpenAPI schema from the running backend and saves it to
 * docs/.vitepress/data/openapi.json.
 *
 * Also generates a Markdown endpoint index at docs/api-reference/endpoints.md.
 *
 * Requires: backend running on localhost:8080 (npm run dev in backend repo)
 *
 * Usage:
 *   node scripts/export-openapi.mjs
 *   npm run openapi:export
 */

import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');
const STATS_DIR = path.resolve(ROOT, 'docs', '.vitepress', 'data');
const API_REF_DIR = path.resolve(ROOT, 'docs', 'api-reference');
const BACKEND_URL = process.env.BACKEND_URL || 'http://localhost:8080';

const METHOD_ORDER = ['get', 'post', 'put', 'patch', 'delete'];

function methodBadge(method) {
  return `<span class="badge-method-${method}">${method.toUpperCase()}</span>`;
}

function escapeCell(value) {
  if (value == null) return '';
  return String(value).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

async function fetchSchema() {
  const url = `${BACKEND_URL}/openapi-dev.json`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  return res.json();
}

function groupEndpoints(schema) {
  const paths = schema.paths || {};
  const byTag = {};

  for (const [routePath, methods] of Object.entries(paths)) {
    for (const method of METHOD_ORDER) {
      const op = methods[method];
      if (!op) continue;
      const tags = op.tags && op.tags.length > 0 ? op.tags : ['untagged'];
      for (const tag of tags) {
        if (!byTag[tag]) byTag[tag] = [];
        byTag[tag].push({ method, path: routePath, op });
      }
    }
  }

  return byTag;
}

function generateEndpointIndex(schema) {
  const byTag = groupEndpoints(schema);
  const ts = new Date().toISOString().replace('T', ' ').replace(/\.\d+Z$/, ' UTC');

  let body = '';
  for (const [tag, endpoints] of Object.entries(byTag).sort(([a], [b]) => a.localeCompare(b))) {
    body += `## ${tag}\n\n`;
    body += '| Method | Path | Summary |\n';
    body += '|--------|------|---------|\n';
    for (const { method, path: p, op } of endpoints) {
      const summary = escapeCell(op.summary || op.operationId || '');
      body += `| ${methodBadge(method)} | \`${escapeCell(p)}\` | ${summary} |\n`;
    }
    body += '\n';
  }

  const totalEndpoints = Object.values(byTag).reduce((acc, e) => acc + e.length, 0);

  return `---
title: API Endpoints
---

<!-- Auto-generated by scripts/export-openapi.mjs on ${ts} -->
<!-- Do not edit manually — run \`npm run openapi:export\` to update. -->

# API Endpoints

> **Version:** ${schema.info?.version || '—'} &nbsp;·&nbsp; **Endpoints:** ${totalEndpoints}

${body}`;
}

async function main() {
  console.log(`Fetching OpenAPI schema from ${BACKEND_URL}/openapi-dev.json...`);

  let schema;
  try {
    schema = await fetchSchema();
  } catch (err) {
    console.error(`Error: ${err.message}`);
    console.error('Make sure the backend is running: cd autopilot-mkt-backend && uvicorn src.main:app --port 8080');
    process.exit(1);
  }

  // Save raw schema JSON for Vue components / tooling
  fs.mkdirSync(STATS_DIR, { recursive: true });
  const jsonDest = path.join(STATS_DIR, 'openapi.json');
  fs.writeFileSync(jsonDest, JSON.stringify(schema, null, 2), 'utf-8');
  console.log(`  Saved ${path.relative(ROOT, jsonDest)}`);

  // Generate endpoint index Markdown
  fs.mkdirSync(API_REF_DIR, { recursive: true });
  const mdDest = path.join(API_REF_DIR, 'endpoints.md');
  fs.writeFileSync(mdDest, generateEndpointIndex(schema), 'utf-8');
  console.log(`  Generated ${path.relative(ROOT, mdDest)}`);

  console.log('Done.');
}

main();
